Controllers/BikeController.cs
using BikeShop.AppDbContext;
using BikeShop.Models;
using BikeShop.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.IO;
using Microsoft.AspNetCore.Hosting.Internal;

namespace BikeShop.Controllers
{
    [Authorize(Roles = "Admin,Executive")]
    public class BikeController : Controller
    {
        // 
        private readonly BikeShopDbContext _db;
        //for image
        private readonly HostingEnvironment _hostingEnvironment;

        //when post or retrive it automatically bind the property
        //dont have to exclusively pass it an object on the association method

        [BindProperty]
        public BikeViewModel BikeVM { get; set; }
        public BikeController(BikeShopDbContext db,HostingEnvironment hostingEnvironment)
        {
            _db = db;

            //LINQ


            BikeVM = new BikeViewModel()
            {
                Makes = _db.Makes.ToList(),
                Models = _db.Models.ToList(),
                Bike = new Models.Bike()

            };
            _hostingEnvironment= hostingEnvironment;
        }
        public IActionResult Index()
        {
            //we just need the name of make and model associated that make
            //we dont need complte  list of makes for our index page
            //we dont need veiw model for our index method
            //we can get the reference of makes associted to any model using eagerloading
            //eagerloading is a process of entity framework whereby a query for one type entity
            //also load related entity as part of the query and we dont need to execute a separate qurey for ralated entities
            //as we already have foreign key reference to make in our model entity we can use eagerloading to load associated makes in our model entity 

            var Bikes = _db.Bikes.Include(m => m.Make).Include(m=>m.Model);
            return View(Bikes.ToList());
        }

        //httpget

        public IActionResult Create()
        {
            return View(BikeVM);
        }
        [HttpPost, ActionName("Create")]
        // [ValidateAntiForgeryToken]
        public IActionResult CreatePost()
        {
            if (!ModelState.IsValid)
            {
                //add it for for nvalid not doing anything and just return in the BikeVM
                BikeVM.Makes = _db.Makes.ToList();
                BikeVM.Models = _db.Models.ToList();

                return View(BikeVM);
            }
            _db.Bikes.Add(BikeVM.Bike);
            // UploadImageIfAvailable();

            _db.SaveChanges();



            ////////////////////////bike logic//////////////////////
            ////////////////////////////////////////////////////////



            // Get BikeID we have saved in database
            var BikeID = BikeVM.Bike.Id;

            //Get wwrootPath to save the file on server
            string wwrootPath = _hostingEnvironment.WebRootPath;

            //Get the Uploaded files
            var files = HttpContext.Request.Form.Files;

            //Get the reference of DBSet for the bike we have saved in our database
            var SavedBike = _db.Bikes.Find(BikeID);


            //Upload the file on server and save the path in database if user have submitted file
            if (files.Count != 0)
            {
                var ImagePath = @"images\bike\";
                //Extract the extension of submitted file
                var Extension = Path.GetExtension(files[0].FileName);

                //Create the relative image path to be saved in database table 
                var RelativeImagePath = ImagePath + BikeID + Extension;

                //Create absolute image path to upload the physical file on server
                var AbsImagePath = Path.Combine(wwrootPath, RelativeImagePath);


                //Upload the file on server using Absolute Path
                using (var filestream = new FileStream(AbsImagePath, FileMode.Create))
                {
                    files[0].CopyTo(filestream);
                }

                //Set the path in database
                SavedBike.ImagePath = RelativeImagePath;
                _db.SaveChanges();

               

            }
            return RedirectToAction(nameof(Index));
        }

        //public IActionResult Edit(int id)
        //{
        //    ModelVM.Model = _db.Models.Include(m => m.Make).SingleOrDefault(m => m.Id == id);
        //    if (ModelVM == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(ModelVM);
        //}

        //[HttpPost]
        //public IActionResult Edit()
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(ModelVM);

        //    }
        //    _db.Update(ModelVM.Model);
        //    _db.SaveChanges();
        //    return RedirectToAction(nameof(Index)); ;

        //}
        [HttpPost]
        public IActionResult Delete(int id)
        {
            //why Bike is type here?
            Bike bike = _db.Bikes.Find(id);
            if (bike == null)
            {
                return NotFound();
            }
            _db.Bikes.Remove(bike);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }



  




    }
}

Controllers/MakeController.cs
using BikeShop.AppDbContext;
using BikeShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace BikeShop.Controllers
{
    [Authorize(Roles="Admin,Executive")]
    public class MakeController : Controller
    {
        private readonly BikeShopDbContext _db;
        public MakeController(BikeShopDbContext db)
        {
            _db = db;   

        }
        public IActionResult Index()
        {
            return View(_db.Makes.ToList());

        }
        //http get method

        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public IActionResult Create(Make make)
        {
            if (ModelState.IsValid)
            {
                _db.Add(make);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(make);

        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var make =_db.Makes.Find(id);
            if(make == null)
            {
                return NotFound();
            }
            _db.Makes.Remove(make);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var make = _db.Makes.Find(id);
            if (make == null)
            {
                return NotFound();
            }

            return View(make);
        }


        [HttpPost]
        public IActionResult Edit(Make make)
        {
            if (ModelState.IsValid)
            {
                _db.Update(make);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(make);    

        }











    }
}

Controllers/ModelController.cs
using BikeShop.AppDbContext;
using BikeShop.Models;
using BikeShop.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace BikeShop.Controllers
{
    [Authorize(Roles = "Admin,Executive")]
    public class ModelController : Controller
    {
        // 
        private readonly BikeShopDbContext _db;

        //when post or retrive it automatically bind the property
        //dont have to exclusively pass it an object on the association method

        [BindProperty]
        public ModelViewModel ModelVM { get; set; }
        public ModelController(BikeShopDbContext db)
        {
            _db = db;

            //LINQ

          
            ModelVM = new ModelViewModel()
            {
                Makes = _db.Makes.ToList(),
                Model = new Models.Model()
            };
        }
        public IActionResult Index()
        {
            //we just need the name of make and model associated that make
            //we dont need complte  list of makes for our index page
            //we dont need veiw model for our index method
            //we can get the reference of makes associted to any model using eagerloading
            //eagerloading is a process of entity framework whereby a query for one type entity
            //also load related entity as part of the query and we dont need to execute a separate qurey for ralated entities
            //as we already have foreign key reference to make in our model entity we can use eagerloading to load associated makes in our model entity 

            var model = _db.Models.Include(m => m.Make);
            return View(model.ToList());
        }

        //httpget

        public IActionResult Create()
        {
            return View(ModelVM);
        }
        [HttpPost,ActionName("Create")]
        public IActionResult CreatePost()
        {
            if(!ModelState.IsValid)
            {
                return View (ModelVM);
            }
            _db.Models.Add(ModelVM.Model);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        public IActionResult Edit(int id)
        {
            ModelVM.Model = _db.Models.Include(m => m.Make).SingleOrDefault(m => m.Id == id);
            if (ModelVM == null)
            {
                return NotFound();
            }

            return View(ModelVM);
        }

        [HttpPost]
        public IActionResult Edit()
        {
            if (!ModelState.IsValid)
            {
                return View(ModelVM);
              
            }
            _db.Update(ModelVM.Model);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index)); ;

        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            Model model = _db.Models.Find(id);
            if (model == null)
            {
                return NotFound();
            }
            _db.Models.Remove(model);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        [AllowAnonymous]
        [HttpGet("api/models/{MakeID}")]

        public IEnumerable<Model> Models(int MakeID)
        {
            return _db.Models.ToList().Where(m=>m.MakeID==MakeID);

        }




    }
}

Views/Shared/_Layout.cshtml
@using BikeShop.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BikeShop</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="https://kit.fontawesome.com/c1c58a5cc0.js" crossorigin="anonymous"></script>
         <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>




    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <script src="https://kit.fontawesome.com/c1c58a5cc0.js" crossorigin="anonymous"></script>
    </environment>
</head>
<body>


    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">BikeShop</a>
       @* <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>*@

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                @*<li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>*@
                @*
                    Interesting.Now masters dropdown list will be only visible to the loged in user.Hurra!!!!!!! 
                *@
                @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Executive))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Masters
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Make" asp-action="Index" >Make</a>
                            <a class="dropdown-item" asp-controller="Model" asp-action="Index" >Models</a>
                             <a class="dropdown-item" asp-controller="Bike" asp-action="Index" >Bikes</a>
                            @if(User.IsInRole(Roles.Admin))
                            {
                                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Add User</a>
                            }
                            @*<div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>*@
                        </div>
                    </li>
                }
                @* <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>*@
            </ul>
            @*<form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>*@
            <partial name ="_LoginPartial" />
        </div>
    </nav>



    <div class="container body-content">
        @RenderBody()
     
        <hr />
        
        <footer>
            <p>&copy; 2022 - BikeShop</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-4.2.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_TableButtonPartial.cshtml
@model int 

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

    <td class="text-right">
        <div class="btn-group" role="group">
            <a type="button" class="btn btn-primary" href="@Url.Action("Edit/"+Model)"><i class="fa-solid fa-pen-to-square"></i></a>
            <form method="post" action="Delete">
                <button onclick="if(!confirm('Are you sure you want to delete?')){return false}" type="submit" class="btn btn-primary rounded-0" asp-action="Delete" asp-route-id="@Model" value="Delete"><i class="fa-solid fa-trash-can"></i></button>
                          
            @* <a type="button" class="btn btn-primary" href="@Url.Action("Delete/"+item.Id)">Delete</a>*@
                </form>
        </div>
    </td>        